/** @type {import('tailwindcss').Config} */
// Design tokens ported verbatim from the "Heritage Earth" system in DESIGN.md.
// These were previously inlined in a <script id="tailwind-config"> block that
// only ran under the browser CDN build.
module.exports = {
  content: ['./index.html'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'inverse-on-surface': '#f8efea',
        'on-primary-fixed': '#370e00',
        'surface-container-high': '#efe6e2',
        'surface-container': '#f5ece7',
        'on-secondary': '#ffffff',
        'surface-tint': '#9b441e',
        'surface-dim': '#e1d8d4',
        'surface-container-lowest': '#ffffff',
        'on-tertiary-fixed': '#1c1c19',
        'clay-muted': '#D9C5B2',
        'inverse-primary': '#ffb599',
        'outline-variant': '#dcc1b7',
        error: '#ba1a1a',
        background: '#ffffff',
        tertiary: '#51504d',
        'tertiary-fixed-dim': '#c9c6c1',
        'on-tertiary-container': '#ece8e3',
        'on-surface-variant': '#56433c',
        'tertiary-container': '#6a6864',
        'on-secondary-fixed': '#291800',
        terracotta: '#A84E27',
        'tertiary-fixed': '#e6e2dd',
        outline: '#89726a',
        'on-primary': '#ffffff',
        'secondary-fixed': '#ffddb3',
        'on-secondary-fixed-variant': '#633f00',
        'on-secondary-container': '#704800',
        'surface-container-low': '#fbf2ed',
        'success-green': '#4A6741',
        'secondary-fixed-dim': '#ffb951',
        'on-error-container': '#93000a',
        'on-error': '#ffffff',
        'on-background': '#1e1b18',
        'primary-fixed-dim': '#ffb599',
        charcoal: '#2D2926',
        'surface-bright': '#fff8f5',
        'surface-container-highest': '#e9e1dc',
        'error-container': '#ffdad6',
        'on-primary-container': '#ffe3d9',
        amber: '#FFB84D',
        'on-tertiary-fixed-variant': '#484743',
        surface: '#ffffff',
        cream: '#F9F5F0',
        'primary-container': '#a84e27',
        primary: '#893711',
        'secondary-container': '#fdb64b',
        secondary: '#825500',
        'inverse-surface': '#34302c',
        'surface-variant': '#e9e1dc',
        'on-surface': '#1e1b18',
        'on-primary-fixed-variant': '#7c2e07',
        'primary-fixed': '#ffdbce',
        'on-tertiary': '#ffffff',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        unit: '8px',
        'section-gap': '80px',
        'margin-mobile': '16px',
        'margin-desktop': '40px',
        gutter: '24px',
        'container-max': '1200px',
      },
      fontFamily: {
        'headline-lg': ['"Source Serif 4"', 'serif'],
        'body-lg': ['"Plus Jakarta Sans"', 'sans-serif'],
        'label-md': ['"Plus Jakarta Sans"', 'sans-serif'],
        'body-md': ['"Plus Jakarta Sans"', 'sans-serif'],
        'headline-md': ['"Source Serif 4"', 'serif'],
        'headline-xl': ['"Source Serif 4"', 'serif'],
        'headline-lg-mobile': ['"Source Serif 4"', 'serif'],
        'label-sm': ['"Plus Jakarta Sans"', 'sans-serif'],
      },
      fontSize: {
        'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.05em', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-xl': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg-mobile': ['28px', { lineHeight: '36px', fontWeight: '700' }],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '500' }],
      },
      maxWidth: {
        'container-max': '1200px',
      },
    },
  },
  plugins: [],
};
